### ISSUE TITLE
Carbon Copy not working / Sending messages to offline buddies

### ISSUE THREAD

**Issue by cyberius0** [Draghtnod/Pidgin-GPG#5]
Hello,

first I want to say a really big _thank you_ for your efforts. OpenPGP is working very good.

(1) I have a problem with carbon copies. My setup is a prosody-0.10 server, Conversations on Android devices and your Pidgin release on Windows.
Now when I write via Pidgin (with OpenPGP) it appears on Conversation. But when I write via Conversations it doesn't appear here on Pidgin.

Do I have to enable it somewhere first? Or should it work right out-of-the-box?

(2) Is it possible to send encrypted OpenPGP messages to offline buddies? If a buddy goes offline then Pidgin says "Encryption disabled, the remote client doesn't support it.". His public key is in Kleopatra and encrypted chatting works when he is online.

**Comment by Draghtnod** [comment]
1) Check Pidgin->Accounts->Your Jabber account->Enable Message Copies
2) It depends. Every OpenPGP supported Client signs its status update to publish its fingerprint. If the last status update was signed, it should work. If not, it won't work even if you got the contact in your Keychain. I'll check the offline feature as i got a bit more time. It works with Conversations, so it should work here too. :)

**Comment by cyberius0** [comment]
(1) Okidoki, I found the setting. It works =)
(2) Oki I understand. It is the same problem with Conversations from time to time so I guess I'll have to live with it ;)
